//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.EmailSecurity.Entity.Test.Entity.EvaluationRules {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RulesResourcesTest {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RulesResourcesTest() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.EmailSecurity.Entity.Test.Entity.EvaluationRules.RulesResourcesTest", typeof(RulesResourcesTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoMatchingMx {
            get {
                return ResourceManager.GetString("NoMatchingMx", resourceCulture);
            }
        }
        
        internal static string NoMatchingMxMarkdown {
            get {
                return ResourceManager.GetString("NoMatchingMxMarkdown", resourceCulture);
            }
        }
        
        internal static string SomeMatchingMx {
            get {
                return ResourceManager.GetString("SomeMatchingMx", resourceCulture);
            }
        }
        
        internal static string SomeMatchingMxMarkdown {
            get {
                return ResourceManager.GetString("SomeMatchingMxMarkdown", resourceCulture);
            }
        }
        
        internal static string TestingSomeError {
            get {
                return ResourceManager.GetString("TestingSomeError", resourceCulture);
            }
        }
        
        internal static string TestingSomeErrorMarkdown {
            get {
                return ResourceManager.GetString("TestingSomeErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string TestingNoneError {
            get {
                return ResourceManager.GetString("TestingNoneError", resourceCulture);
            }
        }
        
        internal static string TestingNoneErrorMarkdown {
            get {
                return ResourceManager.GetString("TestingNoneErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string EnforceSomeError {
            get {
                return ResourceManager.GetString("EnforceSomeError", resourceCulture);
            }
        }
        
        internal static string EnforceSomeErrorMarkdown {
            get {
                return ResourceManager.GetString("EnforceSomeErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string EnforceNoneError {
            get {
                return ResourceManager.GetString("EnforceNoneError", resourceCulture);
            }
        }
        
        internal static string EnforceNoneErrorMarkdown {
            get {
                return ResourceManager.GetString("EnforceNoneErrorMarkdown", resourceCulture);
            }
        }
        
        internal static string GoToEnforce {
            get {
                return ResourceManager.GetString("GoToEnforce", resourceCulture);
            }
        }
        
        internal static string GoToEnforceMarkdown {
            get {
                return ResourceManager.GetString("GoToEnforceMarkdown", resourceCulture);
            }
        }
    }
}
